### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by camilleFournier** [camilleFournier/vue-trivia-app#1]
- [X] Inititiate all screens
- [X] Working quizz
- [x] Add language parameter
- [x] Translate static with plugin
- [x] Translate quizz with API
- [x] Show progress while fetching quizz
- [x] Handle API request issues
- [ ] Redirect to home when navigation not from app
- [x] Redirect to home for undefined routes
- [x] Randomize order of answers
- [ ] Make app responsive
- [ ] Add difficulty parameter
- [ ] Add question type parameter
- [ ] Add progress bar
- [ ] Add 10s countdown for each question
- [ ] Score screen displays questions, answers given and correct answers
- [x] Deploy on Netlify
